# https://school.programmers.co.kr/learn/courses/30/lessons/144856
sql='''
SELECT A.AUTHOR_ID,A.AUTHOR_NAME, B.CATEGORY, SUM(B.PRICE*BS.SALES)
FROM BOOK B JOIN AUTHOR A ON B.AUTHOR_ID=A.AUTHOR_ID
    JOIN BOOK_SALES BS ON B.BOOK_ID=BS.BOOK_ID
WHERE BS.SALES_DATE LIKE '2022-01%'
GROUP BY 2,3
ORDER BY 1,3 DESC
'''