# https://school.programmers.co.kr/learn/courses/30/lessons/131537
sql='''
SELECT DATE_FORMAT(T.SALES_DATE, '%Y-%m-%d') AS SALES_DATE, T.PRODUCT_ID, T.USER_ID, T.SALES_AMOUNT
FROM (
     SELECT SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
      FROM ONLINE_SALE 
     WHERE MONTH(SALES_DATE) = '03'
     UNION ALL 
     SELECT SALES_DATE, PRODUCT_ID, NULL USER_ID, SALES_AMOUNT
      FROM OFFLINE_SALE
     WHERE MONTH(SALES_DATE) = '03'
     ) T
ORDER BY 1, 2,3
'''